export const products = [
    {
        id: 1,
        name: "Custom Shirt",
        category: "Formal Wear",
        price: "₹2,499",
        originalPrice: "₹3,499",
        image: "/placeholder.svg",
        images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
        description: "Premium cotton shirt tailored to perfection with modern design elements.",
        fabric: "Premium Cotton",
        sizes: ["S", "M", "L", "XL"],
        measurements: {
            chest: "38-42",
            waist: "32-36",
            shoulder: "16-18",
        },
        customizations: ["Collar Style", "Cuff Style", "Fit Type", "Monogram"],
        inStock: true,
    },
    {
        id: 2,
        name: "Jersey",
        category: "Sports Wear",
        price: "₹1,999",
        originalPrice: "₹2,499",
        image: "/placeholder.svg",
        images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
        description: "Comfortable jersey perfect for active lifestyle with moisture-wicking fabric.",
        fabric: "Polyester Blend",
        sizes: ["S", "M", "L", "XL", "XXL"],
        measurements: {
            chest: "36-46",
            waist: "30-40",
            shoulder: "15-20",
        },
        customizations: ["Number", "Name", "Sleeve Style"],
        inStock: true,
    },
    {
        id: 3,
        name: "Stretch-Fit Shirt",
        category: "Casual Wear",
        price: "₹2,799",
        originalPrice: "₹3,199",
        image: "/placeholder.svg",
        images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
        description: "Stylish stretch-fit shirt combining comfort with contemporary style.",
        fabric: "Cotton Spandex Blend",
        sizes: ["S", "M", "L", "XL"],
        measurements: {
            chest: "38-42",
            waist: "32-36",
            shoulder: "16-18",
        },
        customizations: ["Color", "Pattern", "Fit Type"],
        inStock: true,
    },
    {
        id: 4,
        name: "Tailored Blazer",
        category: "Formal Wear",
        price: "₹5,999",
        originalPrice: "₹7,999",
        image: "/placeholder.svg",
        images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
        description: "Elegant blazer crafted from fine wool with impeccable tailoring.",
        fabric: "Fine Wool",
        sizes: ["S", "M", "L", "XL"],
        measurements: {
            chest: "40-44",
            waist: "34-40",
            shoulder: "17-19",
        },
        customizations: ["Button Style", "Lining", "Fit Type"],
        inStock: true,
    },
    {
        id: 5,
        name: "Semi-Formal Trousers",
        category: "Formal Wear",
        price: "₹2,199",
        originalPrice: "₹2,899",
        image: "/placeholder.svg",
        images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
        description: "Classic trousers with modern fit and premium fabric.",
        fabric: "Premium Cotton",
        sizes: ["28", "30", "32", "34", "36"],
        measurements: {
            waist: "28-36",
            inseam: "30-34",
            hip: "38-44",
        },
        customizations: ["Fit Type", "Cuff Style", "Pocket Style"],
        inStock: true,
    },
    {
        id: 6,
        name: "Casual Denim Shirt",
        category: "Casual Wear",
        price: "₹1,899",
        originalPrice: "₹2,299",
        image: "/placeholder.svg",
        images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
        description: "Relaxed-fit denim shirt perfect for everyday wear.",
        fabric: "Denim",
        sizes: ["S", "M", "L", "XL"],
        measurements: {
            chest: "38-42",
            waist: "32-36",
            shoulder: "16-18",
        },
        customizations: ["Wash", "Fit Type"],
        inStock: true,
    },
];

export const getProductById = (id) => {
    return products.find((product) => product.id === parseInt(id));
};

export const getProductsByCategory = (category) => {
    return products.filter((product) => product.category === category);
};

