export const products = [
    {
        id: 1,
        name: "Classic Crew T-Shirt",
        category: "T-Shirt",
        price: "₹1,199",
        originalPrice: "₹1,499",
        image: "/placeholder.svg",
        images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
        description: "Premium cotton crew-neck T-shirt designed for everyday comfort and a clean silhouette.",
        fabric: "100% Premium Cotton",
        sizes: ["S", "M", "L", "XL", "XXL"],
        measurements: {
            chest: "36-46",
            waist: "30-40",
            shoulder: "15-20",
        },
        customizations: ["Fit Type", "Sleeve Length", "Neck Style", "Monogram"],
        inStock: true,
    },
    {
        id: 2,
        name: "Athletic Jersey",
        category: "Jersey",
        price: "₹1,999",
        originalPrice: "₹2,499",
        image: "/placeholder.svg",
        images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
        description: "Lightweight performance jersey with moisture-wicking fabric, perfect for sports and active days.",
        fabric: "Polyester Performance Blend",
        sizes: ["S", "M", "L", "XL", "XXL"],
        measurements: {
            chest: "36-48",
            waist: "30-42",
            shoulder: "15-21",
        },
        customizations: ["Number", "Name", "Sleeve Style"],
        inStock: true,
    },
    {
        id: 3,
        name: "Oversized Street T-Shirt",
        category: "T-Shirt",
        price: "₹1,499",
        originalPrice: "₹1,899",
        image: "/placeholder.svg",
        images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
        description: "Relaxed-fit oversized T-shirt with dropped shoulders for a modern streetwear look.",
        fabric: "Cotton Rich Jersey",
        sizes: ["S", "M", "L", "XL"],
        measurements: {
            chest: "40-50",
            waist: "34-44",
            shoulder: "17-22",
        },
        customizations: ["Length", "Print Placement", "Fit Type"],
        inStock: true,
    },
    {
        id: 4,
        name: "Raglan Sleeve Jersey",
        category: "Jersey",
        price: "₹2,199",
        originalPrice: "₹2,799",
        image: "/placeholder.svg",
        images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
        description: "Raglan-sleeve jersey inspired by team kits, ideal for custom squad orders or fan wear.",
        fabric: "Polyester Mesh",
        sizes: ["S", "M", "L", "XL", "XXL"],
        measurements: {
            chest: "38-48",
            waist: "32-42",
            shoulder: "16-21",
        },
        customizations: ["Team Logo", "Player Name", "Number"],
        inStock: true,
    },
    {
        id: 5,
        name: "Essential V-Neck T-Shirt",
        category: "T-Shirt",
        price: "₹1,299",
        originalPrice: "₹1,699",
        image: "/placeholder.svg",
        images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
        description: "Slim-fit V-neck T-shirt that works perfectly on its own or layered under blazers.",
        fabric: "Combed Cotton",
        sizes: ["S", "M", "L", "XL"],
        measurements: {
            chest: "36-44",
            waist: "30-38",
            shoulder: "15-19",
        },
        customizations: ["Neck Depth", "Sleeve Length", "Hem Style"],
        inStock: true,
    },
    {
        id: 6,
        name: "Training Jersey",
        category: "Jersey",
        price: "₹1,899",
        originalPrice: "₹2,299",
        image: "/placeholder.svg",
        images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
        description: "Breathable training jersey with mesh panels to keep you cool during intense sessions.",
        fabric: "High-Performance Polyester",
        sizes: ["S", "M", "L", "XL", "XXL"],
        measurements: {
            chest: "38-48",
            waist: "32-42",
            shoulder: "16-21",
        },
        customizations: ["Fit Type", "Player Name", "Number"],
        inStock: true,
    },
];

export const getProductById = (id) => {
    return products.find((product) => product.id === parseInt(id));
};

export const getProductsByCategory = (category) => {
    return products.filter((product) => product.category === category);
};

